#!/usr/bin/env bash

endpoint="localhost:8080/<bucket>/artifact/<path>/_meta/<item>"
curl -i -L -H "Content-Type: application/json" -H "Authorization: XXXXXXXXXXXXXXXXXXXXXXXXXX" -X PUT \
-d '{"value": "edit this stuff", "immutable": false}' "$endpoint"
