#!/usr/bin/env bash

endpoint="localhost:8080/<bucket>/artifact/<path>/_meta"
curl -i -L -H "Content-Type: application/json" -H "Authorization: XXXXXXXXXXXXXXXXXXXXXX" -X PUT \
-d '{"version":{"value": "1.0", "immutable": false}, "build":{"value": "1","immutable": true}}' "$endpoint"
