#!/usr/bin/env bash

echo "testing file upload with a simple txt file. Woot woot!" > ./upload-test.txt
endpoint="http://localhost:8080/<bucket>/artifact/<path>"
curl -i -L -H -k "Authorization: XXXXXXXXXXXXXXXXXXXXXXXXX" -F "file=@./upload-test.txt" "$endpoint"
rm ./upload-test.txt
