#!/usr/bin/env bash

echo "testing file upload with a simple txt file. Woot woot!" > ./upload-test.txt
endpoint="localhost:8080/artifact/test_folder/upload-test"
curl -i -L -H "Authorization: supersecuretoken" -F "file=@./upload-test.txt" "$endpoint"
rm ./upload-test.txt
